name: izees
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  image_picker: ^1.1.2
  socket_io_client: ^3.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.0.18
  fl_chart: ^1.0.0
  carousel_slider: ^5.0.0
  rxdart: ^0.28.0
  stream_transform: ^2.1.0
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true
  generate: true

  # Localization (optional if not using now)
  # l10n:
  #   arb-dir: lib/l10n
  #   template-arb-file: app_en.arb
  #   output-dir: lib/gen_l10n

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 400

    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400

    - family: IBMPlexSansArabic
      fonts:
      - asset: assets/fonts/Tajawal-Bold.ttf
      - asset: assets/fonts/Tajawal-Medium.ttf
        weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iz.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/iz.png"

flutter_lints: ^3.0.0
